### ISSUE TITLE
Error: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by vkbansal** [vkbansal/eslint-plugin-jsx-control-statements#6]
```
TypeError: Cannot read property 'value' of null
    at E:\projects\frontend\node_modules\eslint-plugin-jsx-control-statements\lib\rules\jsx-for-require-index.js:34:38
    at Array.filter (native)
    at EventEmitter.JSXOpeningElement (E:\projects\frontend\node_modules\eslint-plugin-jsx-control-statements\lib\rules\jsx-for-require-index.js:33:47)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (E:\projects\frontend\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (E:\projects\frontend\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (E:\projects\frontend\node_modules\eslint\lib\eslint.js:767:36)
    at Controller.__execute (E:\projects\frontend\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (E:\projects\frontend\node_modules\estraverse\estraverse.js:495:28)
```

**Comment by vkbansal** [comment]
see #8 

Will remove offending rule completely.
